[package]
name = "jprs"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.31.0", features = ["serialize"] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
serde = { version = "1.0.197", features = ["serde_derive"] }
serde_json = "1.0.115"
thiserror = "1.0.58"
